# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lyne
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'LyneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LyneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
